swagger: "2.0"
info:
  title: color-split-api
  version: 1.0.0
x-google-backend:
  rules:
    - selector: "*"
      address: https://cloudhw3-blue-173777867862.us-central1.run.app
      path_translation: APPEND_PATH_TO_ADDRESS
      deadline: 30.0
    - selector: "*"
      address: https://cloudhw3-green-173777867862.us-central1.run.app
      path_translation: APPEND_PATH_TO_ADDRESS
      deadline: 30.0
paths:
  "/":
    get:
      operationId: getRoot
      responses:
        "200":
          description: OK
  "/{path=**}":
    get:
      operationId: catchAll
      responses:
        "200":
          description: OK
