steps:
  # Access secrets and create files
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud secrets versions access latest --secret=app-env-file > ./server/.env
        gcloud secrets versions access latest --secret=app-service-account > ./server/env.json

  # Determine if branch is blue or green
  - name: "gcr.io/cloud-builders/bash"
    id: "set-env-vars"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        if [[ "$BRANCH_NAME" == "blue" ]]; then
          echo "COLOR=blue" >> /workspace/env_vars
        elif [[ "$BRANCH_NAME" == "green" ]]; then
          echo "COLOR=green" >> /workspace/env_vars
        else
          echo "Invalid branch, exiting"; exit 1
        fi

  # Build the container image with branch-specific tag
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/cloudhw3:$BRANCH_NAME-$COMMIT_SHA",
        "-f",
        "server/Dockerfile",
        "./server",
      ]

  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/cloudhw3:$BRANCH_NAME-$COMMIT_SHA"]

  # Deploy new revision to the Cloud Run service without affecting the other color
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "cloudhw3" # Single Cloud Run service
      - "--image"
      - "gcr.io/$PROJECT_ID/cloudhw3:$BRANCH_NAME-$COMMIT_SHA"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--tag"
      - "$BRANCH_NAME" # Tag the revision as blue or green

  # Set traffic split between the two latest blue and green versions
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "services"
      - "update-traffic"
      - "cloudhw3"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--to-tags"
      - "blue=50,green=50"

images:
  - "gcr.io/$PROJECT_ID/cloudhw3:$BRANCH_NAME-$COMMIT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY
