steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/myapp:$COMMIT_SHA",
        "-f",
        "server/Dockerfile",
        "server/",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/myapp:$COMMIT_SHA"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "${_SERVICE_NAME}"
      - "--image=gcr.io/$PROJECT_ID/myapp:$COMMIT_SHA"
      - "--region=us-central1"
      - "--platform=managed"
      - "--allow-unauthenticated"

options:
  logging: CLOUD_LOGGING_ONLY # Logs will be stored in Cloud Logging

substitutions:
  _SERVICE_NAME: "${BRANCH_NAME}-service"
